{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"7_Exercises","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyMAX+8wEra3YNbHDaF461zw"},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"markdown","metadata":{"id":"EvpDhWStxwwc"},"source":["# Space Age\n","\n","Given an age in seconds, calculate how old someone would be on:\n","\n","    Earth: orbital period 365.25 Earth days, or 31557600 seconds\n","    Mercury: orbital period 0.2408467 Earth years\n","    Venus: orbital period 0.61519726 Earth years\n","    Mars: orbital period 1.8808158 Earth years\n","    Jupiter: orbital period 11.862615 Earth years\n","    Saturn: orbital period 29.447498 Earth years\n","    Uranus: orbital period 84.016846 Earth years\n","    Neptune: orbital period 164.79132 Earth years\n","\n","So if you were told someone were 1,000,000,000 seconds old, you should be able to say that they're 31.69 Earth-years old.\n"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"iXYtqUvKbZg5","executionInfo":{"status":"ok","timestamp":1624751571403,"user_tz":180,"elapsed":240,"user":{"displayName":"Damian Rotta","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhU2mUAYsZwSOXmB7wszaOkG12O7gV_Ksg7rkCpbA=s64","userId":"14266831562328525833"}},"outputId":"11430126-a28b-4da3-c874-334b5241bae8"},"source":["class SpaceAgeTest(unittest.TestCase):\n","\n","    def test_age_on_earth(self):\n","        self.assertEqual(SpaceAge(1000000000).on_earth(), 31.69)\n","    \n","    def test_age_on_mercury(self):\n","        self.assertEqual(SpaceAge(2134835688).on_mercury(), 280.88)\n","\n","    def test_age_on_venus(self):\n","        self.assertEqual(SpaceAge(189839836).on_venus(), 9.78)\n","\n","    def test_age_on_mars(self):\n","        self.assertEqual(SpaceAge(2129871239).on_mars(), 35.88)\n","\n","    def test_age_on_jupiter(self):\n","        self.assertEqual(SpaceAge(901876382).on_jupiter(), 2.41)\n","\n","    def test_age_on_saturn(self):\n","        self.assertEqual(SpaceAge(2000000000).on_saturn(), 2.15)\n","\n","    def test_age_on_uranus(self):\n","        self.assertEqual(SpaceAge(1210123456).on_uranus(), 0.46)\n","\n","    def test_age_on_neptune(self):\n","        self.assertEqual(SpaceAge(1821023456).on_neptune(), 0.35)\n","\n","\n","unittest.main(argv=['first-arg-is-ignored'], exit=False)\n","\n"],"execution_count":null,"outputs":[{"output_type":"stream","text":["........\n","----------------------------------------------------------------------\n","Ran 8 tests in 0.032s\n","\n","OK\n"],"name":"stderr"},{"output_type":"execute_result","data":{"text/plain":["<unittest.main.TestProgram at 0x7f95f076b610>"]},"metadata":{"tags":[]},"execution_count":67}]},{"cell_type":"markdown","metadata":{"id":"rUwBSqOXE8Zd"},"source":["Given a number, find the sum of all the unique multiples of particular numbers up to but not including that number.\n","\n","If we list all the natural numbers below 20 that are multiples of 3 or 5, we get 3, 5, 6, 9, 10, 12, 15, and 18.\n","\n","The sum of these multiples is 78.\n","\n","You can make the following assumptions about the inputs to the sum_of_multiples function:\n","\n","    All input numbers are non-negative ints, i.e. natural numbers including zero.\n","    A list of factors must be given, and its elements are unique and sorted in ascending order.\n"]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"rk4ldZznx4qW","executionInfo":{"status":"ok","timestamp":1624757272024,"user_tz":180,"elapsed":773,"user":{"displayName":"Damian Rotta","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhU2mUAYsZwSOXmB7wszaOkG12O7gV_Ksg7rkCpbA=s64","userId":"14266831562328525833"}},"outputId":"e964d4d3-e810-454d-faae-19fc52092073"},"source":["import unittest\n","\n","\n","class SumOfMultiplesTest(unittest.TestCase):\n","    def test_no_multiples_within_limit(self):\n","        self.assertEqual(sum_of_multiples(1, [3, 5]), 0)\n","\n","    def test_one_factor_has_multiples_within_limit(self):\n","        self.assertEqual(sum_of_multiples(4, [3, 5]), 3)\n","\n","    def test_more_than_one_multiple_within_limit(self):\n","        self.assertEqual(sum_of_multiples(7, [3]), 9)\n","\n","    def test_more_than_one_factor_with_multiples_within_limit(self):\n","        self.assertEqual(sum_of_multiples(10, [3, 5]), 23)\n","\n","    def test_each_multiple_is_only_counted_once(self):\n","        self.assertEqual(sum_of_multiples(100, [3, 5]), 2318)\n","\n","    def test_a_much_larger_limit(self):\n","        self.assertEqual(sum_of_multiples(1000, [3, 5]), 233168)\n","\n","    def test_three_factors(self):\n","        self.assertEqual(sum_of_multiples(20, [7, 13, 17]), 51)\n","\n","    def test_factors_not_relatively_prime(self):\n","        self.assertEqual(sum_of_multiples(15, [4, 6]), 30)\n","\n","    def test_some_pairs_of_factors_relatively_prime_and_some_not(self):\n","        self.assertEqual(sum_of_multiples(150, [5, 6, 8]), 4419)\n","\n","    def test_one_factor_is_a_multiple_of_another(self):\n","        self.assertEqual(sum_of_multiples(51, [5, 25]), 275)\n","\n","    def test_much_larger_factors(self):\n","        self.assertEqual(sum_of_multiples(10000, [43, 47]), 2203160)\n","\n","    def test_all_numbers_are_multiples_of_1(self):\n","        self.assertEqual(sum_of_multiples(100, [1]), 4950)\n","\n","    def test_no_factors_means_an_empty_sum(self):\n","        self.assertEqual(sum_of_multiples(10000, []), 0)\n","\n","    def test_the_only_multiple_of_0_is_0(self):\n","        self.assertEqual(sum_of_multiples(1, [0]), 0)\n","\n","    def test_the_factor_0_does_not_affect_the_sum_of_multiples_of_other_factors(self):\n","        self.assertEqual(sum_of_multiples(4, [3, 0]), 3)\n","\n","    def test_solutions_using_include_exclude_must_extend_to_cardinality_greater_than_3(\n","        self\n","    ):\n","        self.assertEqual(sum_of_multiples(10000, [2, 3, 5, 7, 11]), 39614537)\n","\n","unittest.main(argv=['first-arg-is-ignored'], exit=False)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["........EEEEEEEEEEEEEEEE\n","======================================================================\n","ERROR: test_a_much_larger_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 21, in test_a_much_larger_limit\n","    self.assertEqual(sum_of_multiples(1000, [3, 5]), 233168)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_all_numbers_are_multiples_of_1 (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 39, in test_all_numbers_are_multiples_of_1\n","    self.assertEqual(sum_of_multiples(100, [1]), 4950)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_each_multiple_is_only_counted_once (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 18, in test_each_multiple_is_only_counted_once\n","    self.assertEqual(sum_of_multiples(100, [3, 5]), 2318)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_factors_not_relatively_prime (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 27, in test_factors_not_relatively_prime\n","    self.assertEqual(sum_of_multiples(15, [4, 6]), 30)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_more_than_one_factor_with_multiples_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 15, in test_more_than_one_factor_with_multiples_within_limit\n","    self.assertEqual(sum_of_multiples(10, [3, 5]), 23)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_more_than_one_multiple_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 12, in test_more_than_one_multiple_within_limit\n","    self.assertEqual(sum_of_multiples(7, [3]), 9)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_much_larger_factors (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 36, in test_much_larger_factors\n","    self.assertEqual(sum_of_multiples(10000, [43, 47]), 2203160)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_no_factors_means_an_empty_sum (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 42, in test_no_factors_means_an_empty_sum\n","    self.assertEqual(sum_of_multiples(10000, []), 0)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_no_multiples_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 6, in test_no_multiples_within_limit\n","    self.assertEqual(sum_of_multiples(1, [3, 5]), 0)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_one_factor_has_multiples_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 9, in test_one_factor_has_multiples_within_limit\n","    self.assertEqual(sum_of_multiples(4, [3, 5]), 3)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_one_factor_is_a_multiple_of_another (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 33, in test_one_factor_is_a_multiple_of_another\n","    self.assertEqual(sum_of_multiples(51, [5, 25]), 275)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_solutions_using_include_exclude_must_extend_to_cardinality_greater_than_3 (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 53, in test_solutions_using_include_exclude_must_extend_to_cardinality_greater_than_3\n","    self.assertEqual(sum_of_multiples(10000, [2, 3, 5, 7, 11]), 39614537)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_some_pairs_of_factors_relatively_prime_and_some_not (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 30, in test_some_pairs_of_factors_relatively_prime_and_some_not\n","    self.assertEqual(sum_of_multiples(150, [5, 6, 8]), 4419)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_the_factor_0_does_not_affect_the_sum_of_multiples_of_other_factors (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 48, in test_the_factor_0_does_not_affect_the_sum_of_multiples_of_other_factors\n","    self.assertEqual(sum_of_multiples(4, [3, 0]), 3)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_the_only_multiple_of_0_is_0 (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 45, in test_the_only_multiple_of_0_is_0\n","    self.assertEqual(sum_of_multiples(1, [0]), 0)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_three_factors (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 24, in test_three_factors\n","    self.assertEqual(sum_of_multiples(20, [7, 13, 17]), 51)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","----------------------------------------------------------------------\n","Ran 24 tests in 0.041s\n","\n","FAILED (errors=16)\n"],"name":"stderr"},{"output_type":"execute_result","data":{"text/plain":["<unittest.main.TestProgram at 0x7f95f0773d10>"]},"metadata":{"tags":[]},"execution_count":68}]},{"cell_type":"markdown","metadata":{"id":"e5ZRH0VQUOAm"},"source":["Calculate the number of grains of wheat on a chessboard given that the number on each square doubles.\n","\n","There once was a wise servant who saved the life of a prince. The king promised to pay whatever the servant could dream up. Knowing that the king loved chess, the servant told the king he would like to have grains of wheat. One grain on the first square of a chess board. Two grains on the next. Four on the third, and so on.\n","\n","There are 64 squares on a chessboard.\n","\n","Write code that shows:\n","\n","    how many grains were on each square, and\n","    the total number of grains\n","\n","For bonus points\n","\n","Did you get the tests passing and the code clean? If you want to, these are some additional things you could try:\n","\n","    Optimize for speed.\n","    Optimize for readability."]},{"cell_type":"code","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"mclnvrFXURif","executionInfo":{"status":"ok","timestamp":1624763671157,"user_tz":180,"elapsed":282,"user":{"displayName":"Damian Rotta","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhU2mUAYsZwSOXmB7wszaOkG12O7gV_Ksg7rkCpbA=s64","userId":"14266831562328525833"}},"outputId":"fdf691a9-706e-43aa-8c99-d9338051feb2"},"source":["import unittest\n","\n","\n","class GrainsTest(unittest.TestCase):\n","\n","    def test_1(self):\n","        self.assertEqual(square(1), 1)\n","\n","    def test_2(self):\n","        self.assertEqual(square(2), 2)\n","\n","    def test_3(self):\n","        self.assertEqual(square(3), 4)\n","\n","    def test_4(self):\n","        self.assertEqual(square(4), 8)\n","\n","    def test_16(self):\n","        self.assertEqual(square(16), 32768)\n","\n","    def test_32(self):\n","        self.assertEqual(square(32), 2147483648)\n","\n","    def test_64(self):\n","        self.assertEqual(square(64), 9223372036854775808)\n","\n","    def test_square_0_raises_an_exception(self):\n","        with self.assertRaisesWithMessage(ValueError):\n","            square(0)\n","\n","    def test_negative_square_raises_an_exception(self):\n","        with self.assertRaisesWithMessage(ValueError):\n","            square(-1)\n","\n","    def test_square_greater_than_64_raises_an_exception(self):\n","        with self.assertRaisesWithMessage(ValueError):\n","            square(65)\n","\n","    def test_returns_the_total_number_of_grains_on_the_board(self):\n","        self.assertEqual(total(), 18446744073709551615)\n","\n","    # Utility functions\n","    def assertRaisesWithMessage(self, exception):\n","        return self.assertRaisesRegex(exception, r\".+\")\n","\n","unittest.main(argv=['first-arg-is-ignored'], exit=False)\n"],"execution_count":null,"outputs":[{"output_type":"stream","text":["EEEEEEEEEEE........EEEEEEEEEEEEEEEE\n","======================================================================\n","ERROR: test_1 (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 7, in test_1\n","    self.assertEqual(square(1), 1)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_16 (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 19, in test_16\n","    self.assertEqual(square(16), 32768)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_2 (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 10, in test_2\n","    self.assertEqual(square(2), 2)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_3 (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 13, in test_3\n","    self.assertEqual(square(3), 4)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_32 (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 22, in test_32\n","    self.assertEqual(square(32), 2147483648)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_4 (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 16, in test_4\n","    self.assertEqual(square(4), 8)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_64 (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 25, in test_64\n","    self.assertEqual(square(64), 9223372036854775808)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_negative_square_raises_an_exception (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 33, in test_negative_square_raises_an_exception\n","    square(-1)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_returns_the_total_number_of_grains_on_the_board (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 40, in test_returns_the_total_number_of_grains_on_the_board\n","    self.assertEqual(total(), 18446744073709551615)\n","NameError: name 'total' is not defined\n","\n","======================================================================\n","ERROR: test_square_0_raises_an_exception (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 29, in test_square_0_raises_an_exception\n","    square(0)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_square_greater_than_64_raises_an_exception (__main__.GrainsTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-70-1e20a36f9166>\", line 37, in test_square_greater_than_64_raises_an_exception\n","    square(65)\n","NameError: name 'square' is not defined\n","\n","======================================================================\n","ERROR: test_a_much_larger_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 21, in test_a_much_larger_limit\n","    self.assertEqual(sum_of_multiples(1000, [3, 5]), 233168)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_all_numbers_are_multiples_of_1 (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 39, in test_all_numbers_are_multiples_of_1\n","    self.assertEqual(sum_of_multiples(100, [1]), 4950)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_each_multiple_is_only_counted_once (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 18, in test_each_multiple_is_only_counted_once\n","    self.assertEqual(sum_of_multiples(100, [3, 5]), 2318)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_factors_not_relatively_prime (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 27, in test_factors_not_relatively_prime\n","    self.assertEqual(sum_of_multiples(15, [4, 6]), 30)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_more_than_one_factor_with_multiples_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 15, in test_more_than_one_factor_with_multiples_within_limit\n","    self.assertEqual(sum_of_multiples(10, [3, 5]), 23)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_more_than_one_multiple_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 12, in test_more_than_one_multiple_within_limit\n","    self.assertEqual(sum_of_multiples(7, [3]), 9)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_much_larger_factors (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 36, in test_much_larger_factors\n","    self.assertEqual(sum_of_multiples(10000, [43, 47]), 2203160)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_no_factors_means_an_empty_sum (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 42, in test_no_factors_means_an_empty_sum\n","    self.assertEqual(sum_of_multiples(10000, []), 0)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_no_multiples_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 6, in test_no_multiples_within_limit\n","    self.assertEqual(sum_of_multiples(1, [3, 5]), 0)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_one_factor_has_multiples_within_limit (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 9, in test_one_factor_has_multiples_within_limit\n","    self.assertEqual(sum_of_multiples(4, [3, 5]), 3)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_one_factor_is_a_multiple_of_another (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 33, in test_one_factor_is_a_multiple_of_another\n","    self.assertEqual(sum_of_multiples(51, [5, 25]), 275)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_solutions_using_include_exclude_must_extend_to_cardinality_greater_than_3 (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 53, in test_solutions_using_include_exclude_must_extend_to_cardinality_greater_than_3\n","    self.assertEqual(sum_of_multiples(10000, [2, 3, 5, 7, 11]), 39614537)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_some_pairs_of_factors_relatively_prime_and_some_not (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 30, in test_some_pairs_of_factors_relatively_prime_and_some_not\n","    self.assertEqual(sum_of_multiples(150, [5, 6, 8]), 4419)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_the_factor_0_does_not_affect_the_sum_of_multiples_of_other_factors (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 48, in test_the_factor_0_does_not_affect_the_sum_of_multiples_of_other_factors\n","    self.assertEqual(sum_of_multiples(4, [3, 0]), 3)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_the_only_multiple_of_0_is_0 (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 45, in test_the_only_multiple_of_0_is_0\n","    self.assertEqual(sum_of_multiples(1, [0]), 0)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","======================================================================\n","ERROR: test_three_factors (__main__.SumOfMultiplesTest)\n","----------------------------------------------------------------------\n","Traceback (most recent call last):\n","  File \"<ipython-input-68-01c07433b346>\", line 24, in test_three_factors\n","    self.assertEqual(sum_of_multiples(20, [7, 13, 17]), 51)\n","NameError: name 'sum_of_multiples' is not defined\n","\n","----------------------------------------------------------------------\n","Ran 35 tests in 0.064s\n","\n","FAILED (errors=27)\n"],"name":"stderr"},{"output_type":"execute_result","data":{"text/plain":["<unittest.main.TestProgram at 0x7f95f076b050>"]},"metadata":{"tags":[]},"execution_count":70}]},{"cell_type":"markdown","metadata":{"id":"z2QWHIMixTtA"},"source":["import unittest\n","\n","from prime_factors import factors\n","\n","# Tests adapted from `problem-specifications//canonical-data.json`\n","\n","\n","class PrimeFactorsTest(unittest.TestCase):\n","    def test_no_factors(self):\n","        self.assertEqual(factors(1), [])\n","\n","    def test_prime_number(self):\n","        self.assertEqual(factors(2), [2])\n","\n","    def test_square_of_a_prime(self):\n","        self.assertEqual(factors(9), [3, 3])\n","\n","    def test_cube_of_a_prime(self):\n","        self.assertEqual(factors(8), [2, 2, 2])\n","\n","    def test_product_of_primes_and_non_primes(self):\n","        self.assertEqual(factors(12), [2, 2, 3])\n","\n","    def test_product_of_primes(self):\n","        self.assertEqual(factors(901255), [5, 17, 23, 461])\n","\n","    def test_factors_include_a_large_prime(self):\n","        self.assertEqual(factors(93819012551), [11, 9539, 894119])\n","\n","\n","if __name__ == \"__main__\":\n","    unittest.main()"]}]}